# Generated by Django 5.1 on 2024-10-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_assignmentsubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='course',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='created_by',
            new_name='teacher',
        ),
    ]
