# Generated by Django 5.1 on 2024-09-20 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='registration_code',
        ),
    ]
