# Generated by Django 5.1 on 2024-09-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_remove_teacher_registration_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='registration_code',
            field=models.CharField(default='DEFAULT_CODE', max_length=255),
        ),
    ]
