# Generated by Django 5.1 on 2024-09-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='created_at',
        ),
    ]
