# Generated by Django 5.1 on 2024-09-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_remove_contactmessage_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='phone_number',
            new_name='tel',
        ),
    ]
