# Generated by Django 5.1 on 2024-09-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_course_remove_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='Default Course Name', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=4),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
