# Generated by Django 5.1 on 2024-10-18 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_remove_useranswer_question_remove_useranswer_quiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/experience/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/qualifications/'),
        ),
    ]
