# Generated by Django 5.1 on 2024-10-19 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_alter_teacher_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='myApp.course'),
        ),
        migrations.DeleteModel(
            name='CourseBatch',
        ),
    ]
