# Generated by Django 5.1 on 2024-09-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='auto_generated_password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='auto_generated_username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
