# Generated by Django 5.1 on 2024-10-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_alter_enrollment_course_batch_delete_coursebatch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='course_batch',
            new_name='course',
        ),
    ]
