# Generated by Django 5.1 on 2024-09-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_teacher_auto_generated_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auto_generated_parent_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='auto_generated_parent_username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
