# Generated by Django 5.1 on 2024-09-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_customuser_auto_generated_parent_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_generated_username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('auto_generated_password', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='auto_generated_parent_password',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='auto_generated_parent_username',
        ),
    ]
