# Generated by Django 5.1 on 2024-10-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_course_ending_date_course_starting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
