# Generated by Django 5.1 on 2024-09-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='student_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
