# Generated by Django 5.1 on 2024-10-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_enrollment_enrollment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
