# Generated by Django 5.1 on 2024-09-22 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_classschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.teacher'),
        ),
    ]
