# Generated by Django 5.1 on 2024-10-07 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('starting_time', models.TimeField()),
                ('ending_time', models.TimeField()),
                ('meeting_link', models.URLField()),
                ('interviewer_name', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='myApp.teacher')),
            ],
        ),
    ]
