# Generated by Django 5.1 on 2024-10-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0025_remove_group_members_group_students_group_teachers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
