# Generated by Django 5.1 on 2024-10-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
