# Generated by Django 5.1 on 2024-10-26 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
