# Generated by Django 5.1 on 2024-10-26 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0031_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_replies', to='myApp.teacher'),
        ),
    ]
