# Generated by Django 5.1 on 2024-10-26 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0032_message_reply_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reply_by',
        ),
    ]
