# Generated by Django 5.1 on 2024-10-26 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0033_remove_message_reply_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='teacher_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.teacher'),
        ),
    ]
