# Generated by Django 5.1 on 2024-10-26 03:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0035_remove_message_teacher_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_messages', to='myApp.group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.teacher')),
            ],
        ),
    ]
