# Generated by Django 5.1 on 2024-11-08 15:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0037_quizs_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackquestion',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_questions', to='myApp.course'),
        ),
        migrations.AddField(
            model_name='feedbackquestion',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
