# Generated by Django 5.1 on 2024-11-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0038_feedbackquestion_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackquestion',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackquestion',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
