# Generated by Django 5.1 on 2025-01-13 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0042_uploadedmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('fill_in_the_blank', 'Fill in the Blank'), ('two_mark', '2-Mark Question'), ('six_mark', '6-Mark Question'), ('ten_mark', '10-Mark Question')], max_length=20)),
                ('question_text', models.TextField(unique=True)),
                ('marks', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.uploadedmaterial')),
            ],
        ),
    ]
