# Generated by Django 5.1 on 2025-01-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0043_generatedquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedmaterial',
            name='file',
            field=models.FileField(upload_to='qun_materials/'),
        ),
    ]
