# Generated by Django 5.1 on 2025-01-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0044_alter_uploadedmaterial_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedQuestion',
        ),
    ]
