# Generated by Django 5.1 on 2025-01-29 03:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0049_uploadedmaterial_generatedquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='question_papers/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_marks', models.IntegerField()),
                ('difficulty', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='generatedquestion',
            name='material',
        ),
        migrations.DeleteModel(
            name='AIQuestion',
        ),
        migrations.DeleteModel(
            name='StudyMaterial',
        ),
        migrations.DeleteModel(
            name='GeneratedQuestion',
        ),
        migrations.DeleteModel(
            name='UploadedMaterial',
        ),
    ]
