# Generated by Django 5.1 on 2025-01-31 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0051_elibraryresource_resourcebookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcebookmark',
            name='resource',
        ),
        migrations.AlterUniqueTogether(
            name='resourcebookmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='resourcebookmark',
            name='user',
        ),
        migrations.DeleteModel(
            name='ELibraryResource',
        ),
        migrations.DeleteModel(
            name='ResourceBookmark',
        ),
    ]
