# Generated by Django 5.1 on 2025-02-01 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0053_generatedquestionpaper_assigned_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedquestionpaper',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.teacher'),
        ),
    ]
