# Generated by Django 5.1 on 2025-02-02 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0054_generatedquestionpaper_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedquestionpaper',
            old_name='assigned_course',
            new_name='course',
        ),
        migrations.CreateModel(
            name='MaterialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('key_points', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='myApp.material')),
            ],
        ),
    ]
