# Generated by Django 5.1 on 2025-02-04 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0056_studentfacedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedquestionpaper',
            name='answer_key_file',
            field=models.FileField(blank=True, null=True, upload_to='answer_keys/'),
        ),
        migrations.AlterField(
            model_name='generatedquestionpaper',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.course'),
        ),
        migrations.AlterField(
            model_name='generatedquestionpaper',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.teacher'),
        ),
    ]
