# Generated by Django 5.1 on 2025-02-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0058_course_final_exam_date_course_final_exam_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='final_exam_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='final_exam_duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='passing_percentage',
        ),
        migrations.DeleteModel(
            name='FinalExam',
        ),
    ]
