# Generated by Django 5.1 on 2025-02-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0060_finalexam_finalexamquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfacedata',
            name='is_face_captured',
            field=models.BooleanField(default=False),
        ),
    ]
