# Generated by Django 5.1 on 2025-02-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0061_studentfacedata_is_face_captured'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfacedata',
            name='landmark_data',
            field=models.TextField(null=True),
        ),
    ]
