# Generated by Django 5.1 on 2025-02-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0062_studentfacedata_landmark_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfacedata',
            name='face_encoding',
        ),
        migrations.RemoveField(
            model_name='studentfacedata',
            name='landmark_data',
        ),
        migrations.AddField(
            model_name='studentfacedata',
            name='face_image',
            field=models.ImageField(default='default_face.jpg', upload_to='face_images/'),
        ),
    ]
