# Generated by Django 5.1 on 2025-02-16 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0064_alter_studentfacedata_face_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfacedata',
            name='face_image',
            field=models.ImageField(default='default_face.jpg', upload_to='face_images/'),
        ),
        migrations.CreateModel(
            name='ParentTeacherMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('message_type', models.CharField(choices=[('parent_to_teacher', 'Parent to Teacher'), ('teacher_to_parent', 'Teacher to Parent')], max_length=20)),
                ('subject', models.CharField(default='No Subject', max_length=200)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_messages', to='myApp.parent')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_messages', to='myApp.teacher')),
            ],
            options={
                'verbose_name': 'Parent-Teacher Message',
                'verbose_name_plural': 'Parent-Teacher Messages',
                'ordering': ['-date'],
            },
        ),
    ]
