# Generated by Django 5.1 on 2025-02-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0066_message_media_file_message_message_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text Message'), ('voice', 'Voice Message'), ('video', 'Video Message'), ('image', 'Image Message'), ('pdf', 'PDF Document')], default='text', max_length=10),
        ),
    ]
