# Generated by Django 5.1 on 2025-02-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0067_alter_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermessage',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='teacher_chat_media/'),
        ),
        migrations.AddField(
            model_name='teachermessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text Message'), ('voice', 'Voice Message'), ('video', 'Video Message'), ('image', 'Image Message'), ('pdf', 'PDF Document')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='teachermessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
