# Generated by Django 5.1 on 2025-02-17 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0070_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whiteboardshare',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.teacher'),
        ),
    ]
