# Generated by Django 5.1 on 2025-02-17 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0071_alter_whiteboardshare_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='myApp.calendarevent')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_suggestions', to='myApp.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
