# Generated by Django 5.1 on 2025-02-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0074_teachernote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='applied_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='course',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('personal', 'Personal Leave')], max_length=20),
        ),
    ]
