# Generated by Django 5.1 on 2025-02-26 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0075_alter_leaverequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('human', 'Human'), ('anime', 'Anime'), ('cartoon', 'Cartoon')], default='human', max_length=20)),
                ('skin_tone', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('dark', 'Dark')], default='light', max_length=20)),
                ('hair_color', models.CharField(choices=[('black', 'Black'), ('brown', 'Brown'), ('blonde', 'Blonde'), ('red', 'Red')], default='black', max_length=20)),
                ('eye_color', models.CharField(default='brown', max_length=20)),
                ('accessories', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar_3d_model', models.FileField(blank=True, null=True, upload_to='avatar_models/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
