# Generated by Django 5.1 on 2025-02-28 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0076_studentavatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.teacher'),
        ),
        migrations.DeleteModel(
            name='StudentAvatar',
        ),
    ]
