# Generated by Django 5.1 on 2025-02-28 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0077_leaverequest_handled_by_delete_studentavatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='handled_by',
        ),
    ]
