# Generated by Django 5.1 on 2025-03-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0078_remove_leaverequest_handled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='plagiarism_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='plagiarism_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
