# Generated by Django 5.1 on 2025-03-19 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0080_materialnotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording', models.FileField(upload_to='presentations/recordings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='myApp.course')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.material')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('teacher__teacher_courses__course', models.F('course'))), name='teacher_assigned_to_course')],
            },
        ),
    ]
