# Generated by Django 5.1 on 2025-03-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0081_materialpresentation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='materialpresentation',
            name='teacher_assigned_to_course',
        ),
        migrations.AlterField(
            model_name='materialpresentation',
            name='recording',
            field=models.FileField(blank=True, null=True, upload_to='presentations/recordings/'),
        ),
    ]
