# Generated by Django 5.1 on 2025-03-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0082_remove_materialpresentation_teacher_assigned_to_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialpresentation',
            options={},
        ),
        migrations.AlterField(
            model_name='materialpresentation',
            name='recording',
            field=models.FileField(blank=True, default='default_recording.mp3', null=True, upload_to='presentations/recordings/'),
        ),
    ]
