# Generated by Django 5.1 on 2025-03-19 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0083_alter_materialpresentation_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialPresentation',
        ),
    ]
